extended camera example
lumeohq/onvif-rs pull request #47
Opened 2020-06-24 05:42 UTC by scottlamb

I find it useful to have a more extended example that works easily
out of the box. In particular, one that:

* supports authentication for everything. My cameras require it for
  almost all operations, so eg get_stream_uri didn't work.
* uses real argument parsing so usage is more obvious.
* automatically finds the right URIs for the different SOAP services.
  Also unlike the README examples, my cameras don't let you send
  everything to the root path.
* supports a couple longer operations. They're admittedly a little
  arbitrary.

Not everything works as of this commit, due to media-io/yaserde#76
and at least one other problem.

2020-06-24 11:16 UTC, DmitrySamoylov requested changes

2020-06-24 11:16 UTC, DmitrySamoylov commented on README.md
> +cargo run --example camera -- get_datetime --uri=http://192.168.0.2:8000
Looks like a typo, think the correct command is `get-system-date-and-time`

2020-06-24 11:16 UTC, DmitrySamoylov commented on README.md
> +cargo run --example camera -- set_hostname \
`set-hostname`

2020-06-24 11:16 UTC, DmitrySamoylov commented on README.md
> +cargo run --example camera -- get_stream_uris --uri=http://192.168.0.2:8000
`get-stream-uris`

2020-06-24 11:29 UTC, zeenix approved these changes
Except for what @DmitrySamoylov pointed out, LGTM.

2020-06-25 05:58 UTC, scottlamb commented
Thanks! Fixed the README errors you pointed out. I saw zeenix's fe15362 so I'm trying out this fixup commit thing.

2020-06-25 10:59 UTC, DmitrySamoylov approved these changes

2020-06-25 11:06 UTC, DmitrySamoylov commented
Nice work, thanks! Now you can run `git rebase -i --autosquash` and force-push

2020-06-25 13:37 UTC, victor-soloviev approved these changes

2020-06-25 13:53 UTC, scottlamb commented
Rebased.

2020-06-25 14:11 UTC, merged